# version: '3.8'

# services:
#   frontend:
#     build: .
#     ports:
#       - "3000:80"
#     depends_on:
#       - backend
#     networks:
#       - cms-network

#   # Assuming your backend service configuration
#   backend:
#     # Add your backend service configuration here
#     # image: your-backend-image
#     # ports:
#     #   - "8000:8000"
#     networks:
#       - cms-network

# networks:
#   cms-network:
#     driver: bridge


# version: '3.8'

# services:
#   frontend:
#     build: .
#     ports:
#       - "3010:3000"
#     environment:
#       - REACT_APP_API_URL=https://py-cms.sitepreviews.dev
#       - NODE_ENV=production
#     restart: unless-stopped
#     deploy:
#       resources:
#         limits:
#           memory: "2G"
#     # networks:
#     #   - wp-overlay

# # networks:
#   wp-overlay:
#     external: true



version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=https://py-cms.sitepreviews.dev
      - NODE_ENV=production
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: "512M"
